[package]
name = "mangling"
version = "0.1.0"
authors = ["Darren Kulp <darren@kulp.ch>"]
edition = "2018"
categories = ["development-tools"]
description = "mangling generates safe, recognizable identifiers from byte streams."
license = "MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
regex = "0.2"
