name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-13, windows-latest, ubuntu-latest ]
        rust: [ stable, 1.68.0 ]
        include:
          - os: ubuntu-latest
            rust: beta
          - os: macos-14
            rust: stable

    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  coverage:

    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.3
      with:
        version: '0.16.0'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
